# Generated by Django 5.1.3 on 2024-12-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('idEsp', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEspacio', models.TextField(max_length=250)),
                ('ubicacionEspacio', models.TextField(max_length=250)),
                ('capacidadEspacio', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsu', models.AutoField(primary_key=True, serialize=False)),
                ('apellidoUsuario', models.TextField(max_length=250)),
                ('nombreUsuario', models.TextField(max_length=250)),
                ('correoUsuario', models.EmailField(max_length=254)),
                ('rolUsuario', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHor', models.AutoField(primary_key=True, serialize=False)),
                ('diaHorario', models.TextField(max_length=250)),
                ('horario', models.TextField(max_length=250)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='Estudio.espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idRes', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateField()),
                ('horaInicio', models.TextField(max_length=250)),
                ('horaFinal', models.TextField(max_length=250)),
                ('estadoReserva', models.TextField(max_length=250)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Estudio.espacio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Estudio.usuario')),
            ],
        ),
    ]
